### PR TITLE
Update the link to quickstart for this sample

### PR DESCRIPTION
**Pull request by adriatic**
Please check whether my proposed correction is indeed correct (pun intended :smirk:)

### CODE REVIEW

**Comment by jerriep** [comment]
@adriatic The quickstarts are currently in flux. The "01" sample (for which you updated the readme) is for another quickstart document which is not currently published. So the one you are linking to is not the correct one. As I indicated in #8 things will be broken. 

Once the PR for the updated organization of the .NET quickstarts (https://github.com/auth0/docs/pull/3707) have been merged I will swing around and fix that link.

I have kept #8 open for this purpose, so you will be notified when it has been fixed.

**Comment by adriatic** [comment]
Sorry for stepping into this again, Jerrie 😢

**Comment by jerriep** [comment]
No problem. Just letting you know that it is being tracked. 

Feel free to track the PR as well (https://github.com/auth0/docs/pull/3707), so you can know when to expect resolution of this (more or less ;) )

**Comment by jerriep** [comment]
Most likely will be a couple of weeks still... not sure of the time for resolving this. There are a lot of things which need to come together at the same time

**Comment by adriatic** [comment]
To just point the obvious: my perception of auth0 quick starts and docs (being a newcomer) is completely different than yours: I saw it as complete and already finished, so my intent is to point out a few uncaught imperfection. Your view is likely similar to "boy, what a mess - I have to rearrange and rewrite all this big collection", so my trivial input seems like invented to piss you off. 

Well, that is certainly not my intent; it is something completely different: to create the environment "above" aurelia and auth0 that should simplify the life for both communities of developers. I am discussing this project with @chenkie and am preparing a GitHub organization **`https://github.com/orgs/aurelia-auth0`** where I can create the "real life model" of what I am proposing to do, strictly in the context of the OSS project. 

With your (anticipated) permission, I invited you into this organization, so you can watch what is going on.

**Comment by jerriep** [comment]
The docs were complete. But due to a whole range of circumstances, we decided to hide a particular set of quickstart pages. I decided to not "hide" or delete the related projects in the GithHub project that contains the code for the Quickstart. Therefore the disparity.

Most people approach the code from the quickstart - i.e. they follow the links to the GH repo from the quickstart, so everything is fine.

In your case however you approach it from the other side - by browsing the repo. Therefore you pick up things that are broken temporarily.

Not sure what the intention is of this new GH org?

**Comment by adriatic** [comment]
The new GH org is the beginning of the project run by Auth0 (represented by Ryan Chenkie) and my own team with the following goals

1. Create the new set of Aurelia templates (skeletons, samples ...) that will introduce Auth0 to Aurelia developers. These templates are based on Aurelia's own samples set extended to be "full stack" and use Auth0 PaaS. This work is intended to directly benefit Aurelia community.

2. Using this new Aurelia templates, Ryan asked me to do the reverse implementation serving Auth0 customers who are interested in Aurelia - by taking over  https://github.com/auth0-community/auth0-aurelia-samples.

3. Assuming that all this turns out as good as I expect, we will engage the second stage where we add a layer above all Auth0 samples / quick starts / documentation which will be patterned after our **[Aurelia KendoUI bridge Catalog](http://aurelia-ui-toolkits.github.io/demo-kendo/)** application - something like a Auth0 compendium. In order to better understand this concept, you may decide to visit this "page" 

`http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/grid-basic-use`

and observe that you can edit, run, debug each of the components in this Catalog, with all samples that are created to illustrate aspects of this component.

**Pull request closed without merging**
